# Generated by Django 5.1.6 on 2025-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_winner_auction_item_alter_winner_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
