# Generated by Django 5.1.6 on 2025-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_deliverydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='paid',
        ),
        migrations.AddField(
            model_name='winner',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
